### ISSUE TITLE
Add Degiro as a data feed

### ISSUE THREAD

**Issue by fernandobrito** [fernandobrito/investments-toolkit#10]
Avanza historical price feed is not consistent with TradingView and Degiro. Start migrating away from Avanza to Degiro.

**Comment by Chavithra** [comment]
Hello there,

maybe I can help with that.

My Discord is on my Github profile.

**Comment by Chavithra** [comment]
Forked the project and made a really quick draft on the branch `degiro_draft`.

Hope that can help.

**Comment by fernandobrito** [comment]
@Chavithra Hi! Very exciting to find a stranger writing and contributing to my small pet project!
I'm really curious about how you found this project and how come you even took time to contribute to it 🤩. I added you on Discord (this is my first time using Discord, so let's see if I managed to do it correctly). Thanks a lot for reaching out and contributing.
